[tool.poetry]
name = "audio"
version = "0.1.0"
description = ""
license = "MIT"
authors = []
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
app_config = { path = "../../../libs/config-python" }
app_logger = { path = "../../../libs/logger-python" }
minio_client = { path = "../../../libs/minio-python" }
temporalio = ">=1.15.0,<2.0.0"
numpy = "^2.3.3"
openai-whisper = "^20250625"
pydub = "^0.25.1"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"