[tool.poetry]
name = "minio_client"
version = "0.1.0"
description = ""
authors = []
license = "MIT"
packages = [{include = "minio_client"}]

[tool.poetry.dependencies]
python = ">=3.11,<4"
minio = ">=7.2.15,<8.0.0"
app_config = { path = "../config-python"}


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
