[tool.poetry]
name = "text"
version = "0.1.0"
description = ""
license = "MIT"
authors = []
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
config = { path = "../../../libs/config-python"}
logger = { path = "../../../libs/logger-python"}
minio_client = { path = "../../../libs/minio-python"}
temporalio = ">=1.15.0,<2.0.0"
detoxify = "^0.5.2"
transformers = "^4.55.2"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"