// Code generated by codegen/permissions.go; DO NOT EDIT.
// Source YAML: ./configs/permissions.yaml

package permissions

const (
    // Создание группы задач
    PermTaskGroupCreate = "TASK_GROUP:CREATE"
    // Удаление группы задач
    PermTaskGroupDelete = "TASK_GROUP:DELETE"
    // Чтение информации о группе задач
    PermTaskGroupRead = "TASK_GROUP:READ"
    // Изменение группы задач
    PermTaskGroupUpdate = "TASK_GROUP:UPDATE"
)

// RolePermissions includes the list of permissions for each role
var RolePermissions = map[string][]string{
    "ADMIN": []string{
        PermTaskGroupCreate,
        PermTaskGroupDelete,
        PermTaskGroupRead,
        PermTaskGroupUpdate,
    },
    "USER": []string{
        PermTaskGroupCreate,
        PermTaskGroupRead,
    },
}

// AllPermissions — a list of all permissions (keys)
var AllPermissions = []string{
    PermTaskGroupCreate,
    PermTaskGroupDelete,
    PermTaskGroupRead,
    PermTaskGroupUpdate,
}
