"""Added api token field

Revision ID: 85b21717fc2a
Revises: 8a2bc0769bdf
Create Date: 2023-10-12 15:43:49.957069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b21717fc2a'
down_revision: Union[str, None] = '8a2bc0769bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_token', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_token')
    # ### end Alembic commands ###
