[tool.poetry]
name = "config"
version = "0.1.0"
description = ""
license = "MIT"
authors = []
packages = [{include = "config"}]

[tool.poetry.dependencies]
python = ">=3.11,<4"
dotenv = ">=0.9.9,<0.10.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
